version: "3.8"

services:
  fraud-ocr-api:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: fraud_ocr_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
